query($manageSystem: Boolean!) {
  system {
    info {
      currentVersion @include(if: $manageSystem)
      latestVersion @include(if: $manageSystem)
      groupsTotal
      pagesTotal
      usersTotal
      tagsTotal
    }
  }
}
